apiVersion: apps/v1
kind: Deployment
metadata:
  name: reminder-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reminder-app
  template:
    metadata:
      labels:
        app: reminder-app
    spec:
      containers:
        - name: reminder-app
          image: burns.azurecr.io/reminder-app:main-b77b06a
          command:
            - "./main"
            - "--static=./static"
            - "--tls-cert=/etc/certs/tls.crt"
            - "--tls-key=/etc/certs/tls.key"
            - "--storage=sqlite"
            - "--sqlite-db=/data/data.db"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/localtime
              name: tz-seattle
            - mountPath: /etc/certs
              name: certs
              readOnly: true
            - mountPath: /data
              name: nfs-data
      imagePullSecrets:
        - name: pull-secret
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo/US/Pacific
            type: ""
          name: tz-seattle
        - name: certs
          secret:
            secretName: reminder-certs
        - name: nfs-data
          nfs:
            server: storage.burns.house
            path: /volume1/KubernetesPV
---
apiVersion: v1
kind: Service
metadata:
  name: reminder-app
spec:
  selector:
    app: reminder-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
  type: ClusterIP